# plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# color schema
[[plugins]]
repo = 'cocopon/iceberg.vim'

# file finder
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add= '''
    nnoremap <silent>sd :Denite buffer<CR>
    nnoremap <silent>sr :Denite file/rec<CR>
    nnoremap <silent>sg :Denite grep<CR>
'''

# tree
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    nnoremap <silent><Space>t :NERDTreeToggle<CR>
'''

# show indent
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# auto complete
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
    " Use deoplete.
    let g:deoplete#enable_at_startup = 1
    " Use smartcase.
    "call deoplete#custom#option('smart_case', v:true)
    " use auto select
    set completeopt+=noinsert
    " <C-h>, <BS>: close popup and delete backword char.
    inoremap <expr><C-h> deoplete#smart_close_popup()."<C-h>"
    inoremap <expr><BS>  deoplete#smart_close_popup()."<C-h>"
    inoremap <expr><S-TAB>  pumvisible() ? "<C-p>" : "<S-TAB>" 
    " <CR>: insert selected word \
    imap <expr><CR>  pumvisible() ? "<C-y>" : "<CR>"
'''

# terminal
[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
    let g:neoterm_size = 8
    let g:neoterm_autoscroll = 1
    nnoremap <silent> <Space>c :botright Tnew<CR>
    tnoremap <silent> <ESC> <C-\><C-n>
    tnoremap <silent> jj <C-\><C-n>
    nnoremap <silent> <Space>e :TREPLSendLine<CR>
    vnoremap <silent> <Space>e V:TREPLSendSelection<CR>
'''

# bar
[[plugins]]
repo = 'vim-airline/vim-airline'

# bar thema
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
    let g:AirlineTheme = "minimalist"
'''

# resize window
[[plugins]]
repo = 'simeji/winresizer'

# git
[[plugins]]
repo = "airblade/vim-gitgutter"

# git
[[plugins]]
repo = "tpope/vim-fugitive"
