# dein.vim
[[plugins]]
repo = 'Shougo/dein.vim'

# colorschema
[[plugins]]
repo = 'cocopon/iceberg.vim'

# file open
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
    call denite#custom#var('file_rec', 'command',
        \ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
    call denite#custom#var('grep', 'command', ['ag'])
    call denite#custom#var('grep', 'recursive_opts', [])
    call denite#custom#var('grep', 'final_opts', [])
    call denite#custom#var('grep', 'separator', [])
    call denite#custom#var('grep', 'default_opts',
        \ ['--nocolor', '--nogroup'])
    nnoremap <silent><Space>dc :<C-u>Denite file_rec<CR>
    nnoremap <silent><Space>dg :<C-u>Denite grep<CR>
'''

# tree
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    nnoremap <silent><Space>t :NERDTreeToggle<CR>
'''

# show indent
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'