# deoplete for jedi ok
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

# for flake8 ok
[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = 'python'
hook_post_source = '''
    let g:flake8_quickfix_height=7
    let g:flake8_show_in_gutter=1
    let g:flake8_show_in_file=1
    let g:syntastic_python_flake8_args='--ignore=E501,E225'
    let g:flake8_ignore = 'E501,E225'
    autocmd BufWritePost *.py call Flake8()
'''

[[plugins]]
repo = 'w0rp/ale'
on_ft = 'python'
hook_post_source = '''
    let g:ale_linters = {'python': ['flake8']}
    let g:ale_fixers = {'python': ['autopep8', 'black', 'isort']}

    let g:ale_python_flake8_executable = g:python3_host_prog
    let g:ale_python_flake8_options = '-m flake8'
    let g:ale_python_autopep8_executable = g:python3_host_prog
    let g:ale_python_autopep8_options = '-m autopep8'
    let g:ale_python_isort_executable = g:python3_host_prog
    let g:ale_python_isort_options = '-m isort'
    
    let g:ale_fix_on_save = 1
    let g:ale_sign_column_always = 1
    let g:ale_lint_on_enter = 0
    let g:ale_lint_on_save = 1
    let g:ale_lint_on_text_changed = 'never'
    let g:ale_sign_error = 'EE' 
    let g:ale_sign_warning = 'WW'

    let g:ale_open_list = 1
    let g:ale_keep_list_window_open = 1
    let g:ale_list_vertical = 1

    nmap [ale] <Nop>
    map <Space>l [ale]
    nmap <silent> [ale]<C-P> <Plug>(ale_previous)
    nmap <silent> [ale]<C-N> <Plug>(ale_next)
'''

[[plugins]]
repo = 'godlygeek/tabular' 
on_ft = 'markdown'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
