# dein.vim
[[plugins]]
repo = 'Shougo/dein.vim'

# colorschema
[[plugins]]
repo = 'cocopon/iceberg.vim'

# file open
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
    nnoremap <silent><Space>do :<C-u>Denite file_rec<CR>
    nnoremap <silent><Space>dg :<C-u>Denite grep<CR>
'''

# tree
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    nnoremap <silent><Space>t :NERDTreeToggle<CR>
'''

# show indent
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
